import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Lato, Montserrat } from "next/font/google";
import ChatWidget from "@/components/ChatWidget";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",      // creates a CSS variable
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lato.variable} ${montserrat.variable}`}>
      <body
        className= "antialiased"
      >
        {children}
        {/* Toast container */}
        <Toaster 
          position="top-right" 
          toastOptions={{ duration: 3000 }} 
        />
        <ChatWidget />
      </body>
    </html>
  );
}
